#include "WeatherEntry.h"

// Constructor for WeatherEntry
WeatherEntry::WeatherEntry(std::string _time,
                           double _atTemperature,
                           double _beTemperature,
                           double _bgTemperature,
                           double _chTemperature,
                           double _czTemperature,
                           double _deTemperature,
                           double _dkTemperature,
                           double _eeTemperature,
                           double _esTemperature,
                           double _fiTemperature,
                           double _frTemperature,
                           double _gbTemperature,
                           double _grTemperature,
                           double _hrTemperature,
                           double _huTemperature,
                           double _ieTemperature,
                           double _itTemperature,
                           double _ltTemperature,
                           double _luTemperature,
                           double _lvTemperature,
                           double _nlTemperature,
                           double _noTemperature,
                           double _plTemperature,
                           double _ptTemperature,
                           double _roTemperature,
                           double _seTemperature,
                           double _siTemperature,
                           double _skTemperature)
    : time(_time),
      atTemperature(_atTemperature),
      beTemperature(_beTemperature),
      bgTemperature(_bgTemperature),
      chTemperature(_chTemperature),
      czTemperature(_czTemperature),
      deTemperature(_deTemperature),
      dkTemperature(_dkTemperature),
      eeTemperature(_eeTemperature),
      esTemperature(_esTemperature),
      fiTemperature(_fiTemperature),
      frTemperature(_frTemperature),
      gbTemperature(_gbTemperature),
      grTemperature(_grTemperature),
      hrTemperature(_hrTemperature),
      huTemperature(_huTemperature),
      ieTemperature(_ieTemperature),
      itTemperature(_itTemperature),
      ltTemperature(_ltTemperature),
      luTemperature(_luTemperature),
      lvTemperature(_lvTemperature),
      nlTemperature(_nlTemperature),
      noTemperature(_noTemperature),
      plTemperature(_plTemperature),
      ptTemperature(_ptTemperature),
      roTemperature(_roTemperature),
      seTemperature(_seTemperature),
      siTemperature(_siTemperature),
      skTemperature(_skTemperature)
{
}